# Generated by Django 3.1.12 on 2021-07-11 22:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210711_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=tinymce.models.HTMLField(default='default', verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='article', to='blog.Tag'),
        ),
    ]
