# Generated by Django 3.1.12 on 2021-07-12 00:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210711_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=tinymce.models.HTMLField(verbose_name='short_description'),
        ),
    ]
